# Copyright 2015-2016, Google, Inc.
#
runtime: nodejs
env: flex

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
 - ^node_modules$

env_variables:
  GCLOUD_STORAGE_BUCKET: iradar-specials
